"""Add temple_id to products and redemptions, extend temple fields

Revision ID: 89591f5a584d
Revises: daa9c424e799
Create Date: 2025-12-13 02:55:01.070443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89591f5a584d'
down_revision = 'daa9c424e799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temple_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('low_stock_threshold', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_products_temple_id'), ['temple_id'], unique=False)
        batch_op.create_foreign_key(None, 'temples', ['temple_id'], ['id'])

    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temple_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_redemptions_temple_id'), ['temple_id'], unique=False)
        batch_op.create_foreign_key(None, 'temples', ['temple_id'], ['id'])

    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('website', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('opening_hours', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('checkin_radius', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('checkin_merit_points', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.drop_column('checkin_merit_points')
        batch_op.drop_column('checkin_radius')
        batch_op.drop_column('opening_hours')
        batch_op.drop_column('website')
        batch_op.drop_column('email')
        batch_op.drop_column('phone')
        batch_op.drop_column('images')

    with op.batch_alter_table('redemptions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_redemptions_temple_id'))
        batch_op.drop_column('temple_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_products_temple_id'))
        batch_op.drop_column('low_stock_threshold')
        batch_op.drop_column('temple_id')

    # ### end Alembic commands ###
