"""add_system_admin_tables

Revision ID: 9f3fe56ebf01
Revises: d13b4315867a
Create Date: 2025-12-05 20:46:28.169514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3fe56ebf01'
down_revision = 'd13b4315867a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_admins_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_system_admins_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_admins_username'), ['username'], unique=True)

    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_category', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['system_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_logs_action_category'), ['action_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_logs_created_at'), ['created_at'], unique=False)

    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['system_admins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_settings_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_settings_key'), ['key'], unique=True)

    op.create_table('temple_applications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('temple_name', sa.String(length=100), nullable=False),
    sa.Column('temple_description', sa.Text(), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('deity_main', sa.String(length=50), nullable=True),
    sa.Column('established_year', sa.Integer(), nullable=True),
    sa.Column('certificate_images', sa.JSON(), nullable=True),
    sa.Column('temple_images', sa.JSON(), nullable=True),
    sa.Column('applicant_name', sa.String(length=100), nullable=False),
    sa.Column('applicant_phone', sa.String(length=20), nullable=False),
    sa.Column('applicant_position', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('temple_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['system_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temple_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temple_applications_status'), ['status'], unique=False)

    op.create_table('user_reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('target_type', sa.String(length=30), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_images', sa.JSON(), nullable=True),
    sa.Column('contact_info', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handler_id', sa.Integer(), nullable=True),
    sa.Column('handler_note', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['handler_id'], ['system_admins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_reports_report_type'), ['report_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_reports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reports_status'))
        batch_op.drop_index(batch_op.f('ix_user_reports_report_type'))

    op.drop_table('user_reports')
    with op.batch_alter_table('temple_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temple_applications_status'))

    op.drop_table('temple_applications')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_settings_key'))
        batch_op.drop_index(batch_op.f('ix_system_settings_category'))

    op.drop_table('system_settings')
    with op.batch_alter_table('system_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_system_logs_action_type'))
        batch_op.drop_index(batch_op.f('ix_system_logs_action_category'))

    op.drop_table('system_logs')
    with op.batch_alter_table('system_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_admins_username'))
        batch_op.drop_index(batch_op.f('ix_system_admins_is_active'))
        batch_op.drop_index(batch_op.f('ix_system_admins_email'))

    op.drop_table('system_admins')
    # ### end Alembic commands ###
