"""Add checkin reward system

Revision ID: d13b4315867a
Revises: c63fb12bbf56
Create Date: 2025-12-05 16:26:51.566022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd13b4315867a'
down_revision = 'c63fb12bbf56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkin_rewards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temple_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reward_type', sa.String(length=30), nullable=False),
    sa.Column('condition_value', sa.Integer(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('is_repeatable', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temple_admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temple_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('temple_id', 'user_id', name='unique_temple_user')
    )
    with op.batch_alter_table('temple_admins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temple_admins_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_temple_admins_temple_id'), ['temple_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temple_admins_user_id'), ['user_id'], unique=False)

    op.create_table('temple_announcements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('temple_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temple_announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temple_announcements_is_published'), ['is_published'], unique=False)
        batch_op.create_index(batch_op.f('ix_temple_announcements_temple_id'), ['temple_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_temple_announcements_type'), ['type'], unique=False)

    op.create_table('reward_claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=False),
    sa.Column('points_received', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=20), nullable=True),
    sa.Column('related_checkin_id', sa.Integer(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_checkin_id'], ['checkins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reward_id'], ['checkin_rewards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reward_claims')
    with op.batch_alter_table('temple_announcements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temple_announcements_type'))
        batch_op.drop_index(batch_op.f('ix_temple_announcements_temple_id'))
        batch_op.drop_index(batch_op.f('ix_temple_announcements_is_published'))

    op.drop_table('temple_announcements')
    with op.batch_alter_table('temple_admins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temple_admins_user_id'))
        batch_op.drop_index(batch_op.f('ix_temple_admins_temple_id'))
        batch_op.drop_index(batch_op.f('ix_temple_admins_is_active'))

    op.drop_table('temple_admins')
    op.drop_table('checkin_rewards')
    # ### end Alembic commands ###
