"""Add Temple model and update Checkin with temple relationship

Revision ID: eb5db3c9d7a6
Revises: 26d4566c24be
Create Date: 2025-12-03 21:27:54.778326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb5db3c9d7a6'
down_revision = '26d4566c24be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('main_deity', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('nfc_uid', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temples_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_temples_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_temples_nfc_uid'), ['nfc_uid'], unique=True)

    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temple_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('blessing_points', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_checkins_temple_id'), ['temple_id'], unique=False)
        batch_op.create_foreign_key(None, 'temples', ['temple_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_checkins_temple_id'))
        batch_op.drop_column('blessing_points')
        batch_op.drop_column('notes')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('temple_id')

    with op.batch_alter_table('temples', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temples_nfc_uid'))
        batch_op.drop_index(batch_op.f('ix_temples_name'))
        batch_op.drop_index(batch_op.f('ix_temples_is_active'))

    op.drop_table('temples')
    # ### end Alembic commands ###
