"""add temple events and registrations

Revision ID: f8d1e2c3b4a5
Revises: f3a8b9c2d1e4
Create Date: 2026-01-02 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision = 'f8d1e2c3b4a5'
down_revision = 'f3a8b9c2d1e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 建立 temple_events 表
    op.create_table('temple_events',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('temple_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=200), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('location', sa.String(length=200), nullable=False),
        sa.Column('start_at', sa.DateTime(), nullable=False),
        sa.Column('end_at', sa.DateTime(), nullable=False),
        sa.Column('signup_end_at', sa.DateTime(), nullable=False),
        sa.Column('capacity', sa.Integer(), nullable=False),
        sa.Column('fee', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0.00'),
        sa.Column('cover_image_url', sa.String(length=500), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='draft'),
        sa.Column('created_by', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP')),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_temple_events_creator', ondelete='RESTRICT'),
        sa.ForeignKeyConstraint(['temple_id'], ['temples.id'], name='fk_temple_events_temple', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # 建立 temple_events 索引
    op.create_index('idx_temple_id', 'temple_events', ['temple_id'], unique=False)
    op.create_index('idx_status', 'temple_events', ['status'], unique=False)
    op.create_index('idx_start_at', 'temple_events', ['start_at'], unique=False)
    op.create_index('idx_signup_end_at', 'temple_events', ['signup_end_at'], unique=False)
    op.create_index('idx_created_at', 'temple_events', ['created_at'], unique=False)
    op.create_index('idx_temple_status', 'temple_events', ['temple_id', 'status'], unique=False)

    # 建立 event_registrations 表
    op.create_table('event_registrations',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('event_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=False),
        sa.Column('email', sa.String(length=120), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False, server_default='registered'),
        sa.Column('registered_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('canceled_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['event_id'], ['temple_events.id'], name='fk_event_registrations_event', ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_event_registrations_user', ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # 建立 event_registrations 索引
    op.create_index('idx_event_id', 'event_registrations', ['event_id'], unique=False)
    op.create_index('idx_user_id', 'event_registrations', ['user_id'], unique=False)
    op.create_index('idx_reg_status', 'event_registrations', ['status'], unique=False)
    op.create_index('idx_registered_at', 'event_registrations', ['registered_at'], unique=False)
    op.create_index('idx_event_status', 'event_registrations', ['event_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 刪除 event_registrations 索引
    op.drop_index('idx_event_status', table_name='event_registrations')
    op.drop_index('idx_registered_at', table_name='event_registrations')
    op.drop_index('idx_reg_status', table_name='event_registrations')
    op.drop_index('idx_user_id', table_name='event_registrations')
    op.drop_index('idx_event_id', table_name='event_registrations')

    # 刪除 event_registrations 表
    op.drop_table('event_registrations')

    # 刪除 temple_events 索引
    op.drop_index('idx_temple_status', table_name='temple_events')
    op.drop_index('idx_created_at', table_name='temple_events')
    op.drop_index('idx_signup_end_at', table_name='temple_events')
    op.drop_index('idx_start_at', table_name='temple_events')
    op.drop_index('idx_status', table_name='temple_events')
    op.drop_index('idx_temple_id', table_name='temple_events')

    # 刪除 temple_events 表
    op.drop_table('temple_events')

    # ### end Alembic commands ###
